### ISSUE TITLE
Clicking on events feel too aggressive on desktop

### ISSUE THREAD

**Issue by tmn** [dotkom/glowing-fortnight#14]
See https://github.com/dotKom/glowing-fortnight/issues/10#issuecomment-239741266

**Comment by plusk** [comment]
I looked into this just now (nearly a year later, talk about low priority), and I don't think there's a go-to solution to this. The problems I see here are 1) little space between element you jumped to and top of screen, and 2) the abruptness of the jump. I looked into some alternatives.

Including jQuery seems a bit excessive to me just for the sake of a transition. [scrollIntoView](https://developer.mozilla.org/en/docs/Web/API/Element/scrollIntoView) has somewhat limited support, and nobody seems to support the transition effects, so that's a dead end. [scroll-to-element](https://www.npmjs.com/package/scroll-to-element) is great, however it jumps to the original position of the element when clicked, but that position moves when the original content contracts. That means we just return to the problem we were fixing to begin with here.

We _could_ write our own custom transition, but the time investment outweighs the spoils if you ask me. The problem here is fairly insignificant, so I'm marking this as a #wontfix by closing the issue.
